Generalize zshmark directories.

diff --git a/zsh/zshmarks b/zsh/zshmarks
--- a/zsh/zshmarks
+++ b/zsh/zshmarks
@@ -1,21 +1,33 @@
-MARKDIR=~/.marks
-DROPBOX_DIR=~/Dropbox
-DROPBOX_MARKDIR="$DROPBOX_DIR/.marks"
+# Directory to create marks in by default.
+DEFAULT_MARKDIR=~
 
-mkdir -p "$MARKDIR"
-if [ -d "$DROPBOX_DIR" ]; then
-    mkdir -p "$DROPBOX_MARKDIR"
+# List of directories to store marks in. Any files created under the parent
+# directory will be created in that directory. This is mostly useful when a
+# directory is shared or synced and you want your marks to exist across
+# machines.
+MARKDIRS=("$DEFAULT_MARKDIR")
+
+# Sync marks in Dropbox.
+DROPBOX_DIR=~/Dropbox
+if [[ -d $DROPBOX_DIR ]]; then
+    MARKDIRS=("$DROPBOX_DIR" $MARKDIRS)
 fi
 
-# Add a new mark
+# Create all of the mark directories.
+for MARKDIR in $MARKDIRS; do
+    mkdir -p "$MARKDIR/.marks"
+done
+
+# Add a new mark. The mark will be added to the first mark directory under
+# which it exits or, failing that, the default mark directory.
 mark () {
-    if [ $# -lt 1 -o $# -gt 2 ]; then
-        echo "Usage: mark [TARGET] MARK" >&2
+    if [[ $# -lt 1 || $# -gt 2 ]]; then
+        echo "Usage: $0 [TARGET] MARK" >&2
         return 1
     fi
 
-    if [ $# -eq 2 ]; then
-        if [ ! -d "$1" ]; then
+    if [[ $# -eq 2 ]]; then
+        if [[ ! -d "$1" ]]; then
             echo "$0: not a directory: $1"
             return 1
         fi
@@ -29,59 +41,62 @@ mark () {
     fi
 
     if findmark "$1" > /dev/null 2>&1; then
-        echo "mark: mark already exists: $1" >&2
+        echo "$0: mark already exists: $1" >&2
         return 1
     fi
 
-    if [ "$TARGET" '=~' "^$DROPBOX_DIR/" ]; then
-        echo "$TARGET" > "$DROPBOX_MARKDIR/$1"
-    else
-        echo "$TARGET" > "$MARKDIR/$1"
-    fi
+    MARKDIR="$DEFAULT_MARKDIR"
+    for SUBMARKDIR in $MARKDIRS; do
+        if [[ $TARGET =~ ^$SUBMARKDIR/ ]]; then
+            MARKDIR="$SUBMARKDIR"
+            break
+        fi
+    done
+
+    echo "$TARGET" > "$MARKDIR/.marks/$1"
 }
 
-# List all marks
+# List all marks from all mark directories.
 marks () {
-    if [ $# -gt 0 ]; then
-        echo "Usage: marks" >&2
+    if [[ $# -gt 0 ]]; then
+        echo "Usage: $0" >&2
         return 1
     fi
 
-    find "$MARKDIR" "$DROPBOX_MARKDIR" -type f | while read -r MARKFILE; do
-        MARK="$(basename "$MARKFILE")"
-        TARGET="$(cat "$MARKFILE")"
-        printf "%s -> %s\n" "$MARK" "$TARGET"
+    find ${^MARKDIRS}/.marks -type f | while read -r MARKFILE; do
+        printf "%s -> %s\n" "$MARKFILE:t" "$(cat "$MARKFILE")"
     done
 }
 
-# Print the location of the mark file itself
+# Print the location of the mark file itself.
 findmark () {
-    if [ $# -ne 1 ]; then
-        echo "Usage: findmark MARK" >&2
+    if [[ $# -ne 1 ]]; then
+        echo "Usage: $0 MARK" >&2
         return 1
     fi
 
-    if [ -f "$MARKDIR/$1" ]; then
-        echo "$MARKDIR/$1"
-    elif [ -f "$DROPBOX_MARKDIR/$1" ]; then
-        echo "$DROPBOX_MARKDIR/$1"
-    else
-        echo "$0: no such mark: $1" >&2
-        return 1
-    fi
+    for MARKDIR in $MARKDIRS; do
+        if [[ -f $MARKDIR/.marks/$1 ]]; then
+            echo "$MARKDIR/.marks/$1"
+            return 0
+        fi
+    done
+
+    echo "$0: no such mark: $1" >&2
+    return 1
 }
 
-# Read the target of the mark
+# Read the target of a mark.
 readmark () {
-    if [ $# -lt 1 ]; then
-        echo "Usage: readmark MARK..." >&2
+    if [[ $# -lt 1 ]]; then
+        echo "Usage: $0 MARK..." >&2
         return 1
     fi
 
     error=0
     while [ $# -gt 0 ]; do
         MARK="$(findmark "$1")"
-        if [ $? -eq 0 ]; then
+        if [[ $? -eq 0 ]]; then
             cat "$MARK"
         else
             error=1
@@ -91,32 +106,32 @@ readmark () {
     return error
 }
 
-# Change directories to a mark
+# Change directories to a mark.
 jump () {
-    if [ $# -ne 1 ]; then
-        echo "Usage: jump MARK" >&2
+    if [[ $# -ne 1 ]]; then
+        echo "Usage: $0 MARK" >&2
         return 1
     fi
 
     TARGET="$(readmark "$1")"
-    if [ $? -eq 0 ]; then
+    if [[ $? -eq 0 ]]; then
         cd "$TARGET"
     else
         return 1
     fi
 }
 
-# Remove a mark
+# Remove a mark.
 unmark () {
-    if [ $# -lt 1 ]; then
-        echo "Usage: unmark MARK..." >&2
+    if [[ $# -lt 1 ]]; then
+        echo "Usage: $0 MARK..." >&2
         return 1
     fi
 
     error=0
     while [ $# -gt 0 ]; do
         MARK="$(findmark "$1")"
-        if [ $? -eq 0 ]; then
+        if [[ $? -eq 0 ]]; then
             rm -i "$MARK"
         else
             error=1
